.. Global includes, substitutions, and common links.

.. |author_name| replace:: SmartMonkey Scalable Computing S.L.
.. |author_email| replace:: info@smartmonkey.io
.. |copyright| replace:: Copyright 2019, SmartMonkey Scalable Computing S.L.
.. |project_name| replace:: ``smartmonkey-api-services-python``
.. |project_version| replace:: 0.9.0

.. _issue tracker: https://github.com/smartmonkeyio/smartmonkey-api-services-python/issues
.. _code repository: https://github.com/smartmonkeyio/smartmonkey-api-services-python

.. _git: http://git-scm.org/
.. _github: http://github.com/
.. _pip: http://pypi.python.org/pypi/pip
.. _Python: http://python.org
.. _Flake: https://flake.smartmonkey.io/
.. _`create a new user`: https://flake.smartmonkey.io/register
.. _`API Key`: https://flake.smartmonkey.io/console/keys
.. _`visit our documentation` : http://docs.smartmonkey.io/#/developers/optimization/README?id=input
.. _`requests page`: https://flake.smartmonkey.io/console/requests